name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Unit tests
      id: unit-tests
      uses: education/autograding-python-grader@v1
      with:
        timeout: 1
        setup-command: ''
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        UNIT-TESTS_RESULTS: "${{steps.unit-tests.outputs.result}}"
      with:
        runners: unit-tests
